window.PVZ2_PLANTS = [
  { id:"peashooter", en:"Peashooter", name:"Горохострел", icon:"🟢", sun:"100", recharge:"5", world:"Player's House", worldRu:"Дом игрока", types:["pea"] },
  { id:"sunflower", en:"Sunflower", name:"Подсолнух", icon:"☀️", sun:"50", recharge:"5", world:"Player's House", worldRu:"Дом игрока", types:["sun"] },
  { id:"wall-nut", en:"Wall-nut", name:"Стенорех", icon:"🛡️", sun:"50", recharge:"20", world:"Player's House", worldRu:"Дом игрока", types:["defense"] },
  { id:"potato-mine", en:"Potato Mine", name:"Картофельная мина", icon:"💣", sun:"25", recharge:"20", world:"Player's House", worldRu:"Дом игрока", types:["bomb"] },
  { id:"cabbage-pult", en:"Cabbage-pult", name:"Капустопульта", icon:"🎯", sun:"100", recharge:"5", world:"Player's House", worldRu:"Дом игрока", types:["lobber"] },
  { id:"bloomerang", en:"Bloomerang", name:"Бумеранг-цветок", icon:"🟢", sun:"175", recharge:"5", world:"Ancient Egypt", worldRu:"Древний Египет", types:["pea"] },
  { id:"iceberg-lettuce", en:"Iceberg Lettuce", name:"Айсберг-салат", icon:"🧊", sun:"0", recharge:"20", world:"Ancient Egypt", worldRu:"Древний Египет", types:["ice"] },
  { id:"grave-buster", en:"Grave Buster", name:"Могилоглот", icon:"🌱", sun:"0", recharge:"10", world:"Ancient Egypt", worldRu:"Древний Египет", types:["other"] },
  { id:"bonk-choy", en:"Bonk Choy", name:"Ударный чой", icon:"👊", sun:"150", recharge:"5", world:"Ancient Egypt", worldRu:"Древний Египет", types:["melee"] },
  { id:"repeater", en:"Repeater", name:"Двойной горохострел", icon:"🟢", sun:"200", recharge:"5", world:"Ancient Egypt", worldRu:"Древний Египет", types:["pea"] },
  { id:"twin-sunflower", en:"Twin Sunflower", name:"Двойной подсолнух", icon:"☀️", sun:"125", recharge:"10", world:"Ancient Egypt", worldRu:"Древний Египет", types:["sun"] },
  { id:"kernel-pult", en:"Kernel-pult", name:"Кукурузомёт", icon:"🎯", sun:"100", recharge:"5", world:"Pirate Seas", worldRu:"Пиратские моря", types:["lobber"] },
  { id:"snapdragon", en:"Snapdragon", name:"Дракончик", icon:"🔥", sun:"150", recharge:"5", world:"Pirate Seas", worldRu:"Пиратские моря", types:["fire"] },
  { id:"spikeweed", en:"Spikeweed", name:"Шипокуст", icon:"📌", sun:"100", recharge:"5", world:"Pirate Seas", worldRu:"Пиратские моря", types:["spike"] },
  { id:"spring-bean", en:"Spring Bean", name:"Пружинный боб", icon:"🌱", sun:"50", recharge:"20", world:"Pirate Seas", worldRu:"Пиратские моря", types:["other"] },
  { id:"coconut-cannon", en:"Coconut Cannon", name:"Кокосовая пушка", icon:"🌱", sun:"400", recharge:"5", world:"Pirate Seas", worldRu:"Пиратские моря", types:["other"] },
  { id:"threepeater", en:"Threepeater", name:"Тройной горохострел", icon:"🟢", sun:"300", recharge:"5", world:"Pirate Seas", worldRu:"Пиратские моря", types:["pea"] },
  { id:"spikerock", en:"Spikerock", name:"Шипокамень", icon:"📌", sun:"250", recharge:"5", world:"Pirate Seas", worldRu:"Пиратские моря", types:["spike"] },
  { id:"cherry-bomb", en:"Cherry Bomb", name:"Вишня-бомба", icon:"💣", sun:"150", recharge:"35", world:"Pirate Seas", worldRu:"Пиратские моря", types:["bomb"] },
  { id:"split-pea", en:"Split Pea", name:"Разрезной горох", icon:"🟢", sun:"125", recharge:"5", world:"Wild West", worldRu:"Дикий Запад", types:["pea"] },
  { id:"chili-bean", en:"Chili Bean", name:"Чили-боб", icon:"🔥", sun:"50", recharge:"20", world:"Wild West", worldRu:"Дикий Запад", types:["fire"] },
  { id:"pea-pod", en:"Pea Pod", name:"Гороховый стручок", icon:"🟢", sun:"125", recharge:"5", world:"Wild West", worldRu:"Дикий Запад", types:["pea"] },
  { id:"lightning-reed", en:"Lightning Reed", name:"Молниевый тростник", icon:"⚡", sun:"125", recharge:"5", world:"Wild West", worldRu:"Дикий Запад", types:["electric"] },
  { id:"melon-pult", en:"Melon-pult", name:"Арбузомёт", icon:"🎯", sun:"325", recharge:"5", world:"Wild West", worldRu:"Дикий Запад", types:["lobber"] },
  { id:"tall-nut", en:"Tall-nut", name:"Высокий орех", icon:"🛡️", sun:"125", recharge:"20", world:"Wild West", worldRu:"Дикий Запад", types:["defense"] },
  { id:"winter-melon", en:"Winter Melon", name:"Зимний арбуз", icon:"🧊", sun:"500", recharge:"5", world:"Wild West", worldRu:"Дикий Запад", types:["ice","lobber"] },
  { id:"hot-potato", en:"Hot Potato", name:"Горячая картошка", icon:"🔥", sun:"0", recharge:"10", world:"Frostbite Caves", worldRu:"Ледяные пещеры", types:["fire"] },
  { id:"pepper-pult", en:"Pepper-pult", name:"Перечномёт", icon:"🔥", sun:"200", recharge:"20", world:"Frostbite Caves", worldRu:"Ледяные пещеры", types:["fire","lobber"] },
  { id:"chard-guard", en:"Chard Guard", name:"Мангольд-страж", icon:"🛡️", sun:"75", recharge:"15", world:"Frostbite Caves", worldRu:"Ледяные пещеры", types:["defense"] },
  { id:"stunion", en:"Stunion", name:"Лукоглушитель", icon:"✨", sun:"25", recharge:"20", world:"Frostbite Caves", worldRu:"Ледяные пещеры", types:["support"] },
  { id:"rotobaga", en:"Rotobaga", name:"Ротобага", icon:"🌱", sun:"150", recharge:"5", world:"Frostbite Caves", worldRu:"Ледяные пещеры", types:["other"] },
  { id:"red-stinger", en:"Red Stinger", name:"Красный жалонос", icon:"🟢", sun:"150", recharge:"5", world:"Lost City", worldRu:"Затерянный город", types:["pea"] },
  { id:"a-k-e-e", en:"A.K.E.E.", name:"А.К.Е.Е.", icon:"🌱", sun:"175", recharge:"5", world:"Lost City", worldRu:"Затерянный город", types:["other"] },
  { id:"endurian", en:"Endurian", name:"Дуриан", icon:"🛡️", sun:"100", recharge:"15", world:"Lost City", worldRu:"Затерянный город", types:["defense"] },
  { id:"stallia", en:"Stallia", name:"Замедляйка", icon:"✨", sun:"0", recharge:"20", world:"Lost City", worldRu:"Затерянный город", types:["support"] },
  { id:"gold-leaf", en:"Gold Leaf", name:"Золотой лист", icon:"☀️", sun:"80", recharge:"50", world:"Lost City", worldRu:"Затерянный город", types:["sun"] },
  { id:"laser-bean", en:"Laser Bean", name:"Лазерный боб", icon:"🌱", sun:"200", recharge:"5", world:"Far Future", worldRu:"Далёкое будущее", types:["other"] },
  { id:"blover", en:"Blover", name:"Дутик", icon:"✨", sun:"50", recharge:"5", world:"Far Future", worldRu:"Далёкое будущее", types:["support"] },
  { id:"citron", en:"Citron", name:"Цитрон", icon:"🌱", sun:"350", recharge:"5", world:"Far Future", worldRu:"Далёкое будущее", types:["other"] },
  { id:"e-m-peach", en:"E.M.Peach", name:"ЭМИ-персик", icon:"⚡", sun:"25", recharge:"25", world:"Far Future", worldRu:"Далёкое будущее", types:["electric","pea"] },
  { id:"infi-nut", en:"Infi-nut", name:"Вечно-орех", icon:"🛡️", sun:"75", recharge:"15", world:"Far Future", worldRu:"Далёкое будущее", types:["defense"] },
  { id:"magnifying-grass", en:"Magnifying Grass", name:"Трава-лупа", icon:"☀️", sun:"50", recharge:"5", world:"Far Future", worldRu:"Далёкое будущее", types:["sun"] },
  { id:"tile-turnip", en:"Tile Turnip", name:"Репа-плитка", icon:"🌱", sun:"0 > 250 > Г—2", recharge:"10", world:"Far Future", worldRu:"Далёкое будущее", types:["other"] },
  { id:"sun-shroom", en:"Sun-shroom", name:"Солнцегриб", icon:"☀️", sun:"25", recharge:"5", world:"Dark Ages", worldRu:"Тёмные века", types:["sun"] },
  { id:"puff-shroom", en:"Puff-shroom", name:"Пуф-гриб", icon:"🌱", sun:"0", recharge:"5", world:"Dark Ages", worldRu:"Тёмные века", types:["other"] },
  { id:"fume-shroom", en:"Fume-shroom", name:"Дымогриб", icon:"☠️", sun:"125", recharge:"5", world:"Dark Ages", worldRu:"Тёмные века", types:["poison"] },
  { id:"sun-bean", en:"Sun Bean", name:"Солнечный боб", icon:"☀️", sun:"50", recharge:"20", world:"Dark Ages", worldRu:"Тёмные века", types:["sun"] },
  { id:"magnet-shroom", en:"Magnet-shroom", name:"Магнитогриб", icon:"🌱", sun:"100", recharge:"15", world:"Dark Ages", worldRu:"Тёмные века", types:["other"] },
  { id:"phat-beet", en:"Phat Beet", name:"Жирная свёкла", icon:"🌱", sun:"150", recharge:"5", world:"Neon Mixtape Tour", worldRu:"Неоновый тур", types:["other"] },
  { id:"celery-stalker", en:"Celery Stalker", name:"Сельдерей-сталкер", icon:"👊", sun:"50", recharge:"15", world:"Neon Mixtape Tour", worldRu:"Неоновый тур", types:["melee"] },
  { id:"thyme-warp", en:"Thyme Warp", name:"Чабрец-сдвиг", icon:"✨", sun:"100", recharge:"90", world:"Neon Mixtape Tour", worldRu:"Неоновый тур", types:["support"] },
  { id:"garlic", en:"Garlic", name:"Чеснок", icon:"✨", sun:"50", recharge:"20", world:"Neon Mixtape Tour", worldRu:"Неоновый тур", types:["support"] },
  { id:"spore-shroom", en:"Spore-shroom", name:"Спорогриб", icon:"☠️", sun:"150", recharge:"5", world:"Neon Mixtape Tour", worldRu:"Неоновый тур", types:["poison"] },
  { id:"intensive-carrot", en:"Intensive Carrot", name:"Интенсивная морковь", icon:"✨", sun:"100", recharge:"20", world:"Neon Mixtape Tour", worldRu:"Неоновый тур", types:["support"] },
  { id:"primal-peashooter", en:"Primal Peashooter", name:"Древний горохострел", icon:"🟢", sun:"175", recharge:"5", world:"Jurassic Marsh", worldRu:"Юрское болото", types:["pea"] },
  { id:"primal-wall-nut", en:"Primal Wall-nut", name:"Древний орех", icon:"🛡️", sun:"75", recharge:"5", world:"Jurassic Marsh", worldRu:"Юрское болото", types:["defense"] },
  { id:"perfume-shroom", en:"Perfume-shroom", name:"Парфюмогриб", icon:"✨", sun:"150", recharge:"30", world:"Jurassic Marsh", worldRu:"Юрское болото", types:["support","poison"] },
  { id:"primal-sunflower", en:"Primal Sunflower", name:"Древний подсолнух", icon:"☀️", sun:"75", recharge:"5", world:"Jurassic Marsh", worldRu:"Юрское болото", types:["sun"] },
  { id:"primal-potato-mine", en:"Primal Potato Mine", name:"Древняя мина", icon:"💣", sun:"50", recharge:"25", world:"Jurassic Marsh", worldRu:"Юрское болото", types:["bomb"] },
  { id:"lily-pad", en:"Lily Pad", name:"Кувшинка", icon:"🌊", sun:"25", recharge:"5", world:"Big Wave Beach", worldRu:"Большая волна", types:["water"] },
  { id:"tangle-kelp", en:"Tangle Kelp", name:"Водоросль-ловушка", icon:"🌊", sun:"25", recharge:"20", world:"Big Wave Beach", worldRu:"Большая волна", types:["water"] },
  { id:"bowling-bulb", en:"Bowling Bulb", name:"Кегельная луковица", icon:"🌊", sun:"200", recharge:"5", world:"Big Wave Beach", worldRu:"Большая волна", types:["water"] },
  { id:"guacodile", en:"Guacodile", name:"Гуакадил", icon:"🌊", sun:"125", recharge:"5", world:"Big Wave Beach", worldRu:"Большая волна", types:["water"] },
  { id:"banana-launcher", en:"Banana Launcher", name:"Бананомёт", icon:"🌊", sun:"500", recharge:"5", world:"Big Wave Beach", worldRu:"Большая волна", types:["water"] },
  { id:"moonflower", en:"Moonflower", name:"Лунный цветок", icon:"🌑", sun:"50", recharge:"10", world:"Modern Day", worldRu:"Современность", types:["shadow"] },
  { id:"nightshade", en:"Nightshade", name:"Паслён", icon:"🌑", sun:"75", recharge:"5", world:"Modern Day", worldRu:"Современность", types:["shadow"] },
  { id:"shadow-shroom", en:"Shadow-shroom", name:"Тенегриб", icon:"🌑", sun:"50", recharge:"10", world:"Modern Day", worldRu:"Современность", types:["shadow","poison"] },
  { id:"dusk-lobber", en:"Dusk Lobber", name:"Сумеречный метатель", icon:"🌑", sun:"150", recharge:"10", world:"Modern Day", worldRu:"Современность", types:["shadow","lobber"] },
  { id:"grimrose", en:"Grimrose", name:"Мрачная роза", icon:"🌑", sun:"75", recharge:"20", world:"Modern Day", worldRu:"Современность", types:["shadow"] },
  { id:"snow-pea", en:"Snow Pea", name:"Снежный горох", icon:"🧊", sun:"150", recharge:"5", world:"Premium", worldRu:"Премиум", types:["ice","pea"] },
  { id:"power-lily", en:"Power Lily", name:"Силовая лилия", icon:"☀️", sun:"175", recharge:"60", world:"Premium", worldRu:"Премиум", types:["sun"] },
  { id:"squash", en:"Squash", name:"Кабачок", icon:"🌱", sun:"50", recharge:"20", world:"Premium", worldRu:"Премиум", types:["other"] },
  { id:"jalapeno", en:"Jalapeno", name:"Халапеньо", icon:"🔥", sun:"125", recharge:"35", world:"Premium", worldRu:"Премиум", types:["fire"] },
  { id:"imitater", en:"Imitater", name:"Имитатор", icon:"✨", sun:"Same as the imitated plant.", recharge:"Same as the imitated plant.", world:"Premium", worldRu:"Премиум", types:["support"] },
  { id:"hypno-shroom", en:"Hypno-shroom", name:"Гипногриб", icon:"✨", sun:"125", recharge:"20", world:"Premium", worldRu:"Премиум", types:["support"] },
  { id:"pea-nut", en:"Pea-nut", name:"Горохорех", icon:"🛡️", sun:"150", recharge:"15", world:"Premium", worldRu:"Премиум", types:["defense","pea"] },
  { id:"chomper", en:"Chomper", name:"Чомпер", icon:"👊", sun:"150", recharge:"5", world:"Premium", worldRu:"Премиум", types:["melee"] },
  { id:"homing-thistle", en:"Homing Thistle", name:"Самонаводящийся чертополох", icon:"🌱", sun:"250", recharge:"15", world:"Premium", worldRu:"Премиум", types:["other"] },
  { id:"ghost-pepper", en:"Ghost Pepper", name:"Призрачный перец", icon:"🔥", sun:"75", recharge:"15", world:"Premium", worldRu:"Премиум", types:["fire"] },
  { id:"sweet-potato", en:"Sweet Potato", name:"Батат", icon:"✨", sun:"150", recharge:"20", world:"Premium", worldRu:"Премиум", types:["support"] },
  { id:"sap-fling", en:"Sap-fling", name:"Смоляной росток", icon:"✨", sun:"75", recharge:"5", world:"Premium", worldRu:"Премиум", types:["support"] },
  { id:"hurrikale", en:"Hurrikale", name:"Ураганная капуста", icon:"🧊", sun:"100", recharge:"15", world:"Premium", worldRu:"Премиум", types:["ice"] },
  { id:"fire-peashooter", en:"Fire Peashooter", name:"Огненный горохострел", icon:"🔥", sun:"175", recharge:"5", world:"Premium", worldRu:"Премиум", types:["fire","pea"] },
  { id:"lava-guava", en:"Lava Guava", name:"Лавовая гуава", icon:"🔥", sun:"75", recharge:"15", world:"Premium", worldRu:"Премиум", types:["fire"] },
  { id:"toadstool", en:"Toadstool", name:"Жабоягодник", icon:"🌱", sun:"200", recharge:"5", world:"Premium", worldRu:"Премиум", types:["other"] },
  { id:"strawburst", en:"Strawburst", name:"Клубничный взрыв", icon:"🎯", sun:"400", recharge:"5", world:"Premium", worldRu:"Премиум", types:["lobber"] },
  { id:"cactus", en:"Cactus", name:"Кактус", icon:"📌", sun:"175", recharge:"5", world:"Premium", worldRu:"Премиум", types:["spike"] },
  { id:"electric-blueberry", en:"Electric Blueberry", name:"Электрочерника", icon:"⚡", sun:"150", recharge:"45", world:"Premium", worldRu:"Премиум", types:["electric"] },
  { id:"jack-o-lantern", en:"Jack O' Lantern", name:"Светильник Джека", icon:"🔥", sun:"225", recharge:"20", world:"Premium", worldRu:"Премиум", types:["fire"] },
  { id:"grapeshot", en:"Grapeshot", name:"Виноградный заряд", icon:"💣", sun:"150", recharge:"35", world:"Premium", worldRu:"Премиум", types:["bomb"] },
  { id:"cold-snapdragon", en:"Cold Snapdragon", name:"Ледяной дракончик", icon:"🔥", sun:"150", recharge:"5", world:"Premium", worldRu:"Премиум", types:["fire","ice"] },
  { id:"shrinking-violet", en:"Shrinking Violet", name:"Уменьшающая фиалка", icon:"✨", sun:"50", recharge:"15", world:"Premium", worldRu:"Премиум", types:["support"] },
  { id:"escape-root", en:"Escape Root", name:"Корень-побег", icon:"✨", sun:"50", recharge:"20", world:"Premium", worldRu:"Премиум", types:["support"] },
  { id:"gold-bloom", en:"Gold Bloom", name:"Золотой бутон", icon:"☀️", sun:"0", recharge:"75", world:"Premium", worldRu:"Премиум", types:["sun"] },
  { id:"electric-currant", en:"Electric Currant", name:"Электросмородина", icon:"⚡", sun:"150", recharge:"10", world:"Premium", worldRu:"Премиум", types:["electric"] },
  { id:"wasabi-whip", en:"Wasabi Whip", name:"Васаби-кнут", icon:"🔥", sun:"150", recharge:"5", world:"Premium", worldRu:"Премиум", types:["fire","melee"] },
  { id:"kiwibeast", en:"Kiwibeast", name:"Киви-зверь", icon:"🌱", sun:"175", recharge:"15", world:"Premium", worldRu:"Премиум", types:["other"] },
  { id:"apple-mortar", en:"Apple Mortar", name:"Яблочная мортира", icon:"🎯", sun:"250", recharge:"8", world:"Premium", worldRu:"Премиум", types:["lobber"] },
  { id:"witch-hazel", en:"Witch Hazel", name:"Ведьмина лещина", icon:"🌱", sun:"200", recharge:"30", world:"Premium", worldRu:"Премиум", types:["other"] },
  { id:"parsnip", en:"Parsnip", name:"Пастернак", icon:"👊", sun:"150", recharge:"5", world:"Premium", worldRu:"Премиум", types:["melee"] },
  { id:"missile-toe", en:"Missile Toe", name:"Ракетный палец", icon:"🧊", sun:"500", recharge:"5", world:"Premium", worldRu:"Премиум", types:["ice"] },
  { id:"caulipower", en:"Caulipower", name:"Гипноцветная капуста", icon:"🌱", sun:"250", recharge:"45", world:"Premium", worldRu:"Премиум", types:["other"] },
  { id:"electric-peashooter", en:"Electric Peashooter", name:"Электро-горохострел", icon:"⚡", sun:"200", recharge:"5", world:"Premium", worldRu:"Премиум", types:["electric","pea"] },
  { id:"holly-barrier", en:"Holly Barrier", name:"Падуб-барьер", icon:"🛡️", sun:"150", recharge:"15", world:"Premium", worldRu:"Премиум", types:["defense"] },
  { id:"torchwood", en:"Torchwood", name:"Факельное дерево", icon:"🔥", sun:"175", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire"] },
  { id:"starfruit", en:"Starfruit", name:"Звездофрукт", icon:"🟢", sun:"150", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["pea"] },
  { id:"dandelion", en:"Dandelion", name:"Одуванчик", icon:"🌱", sun:"275", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"blooming-heart", en:"Blooming Heart", name:"Цветущее сердце", icon:"🌱", sun:"150", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"explode-o-nut", en:"Explode-O-Nut", name:"Взрыворех", icon:"💣", sun:"50", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb"] },
  { id:"aloe", en:"Aloe", name:"Алоэ", icon:"✨", sun:"75", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["support"] },
  { id:"bombegranate", en:"Bombegranate", name:"Гранатобомба", icon:"💣", sun:"150", recharge:"35", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb"] },
  { id:"hot-date", en:"Hot Date", name:"Горячий финик", icon:"🔥", sun:"175", recharge:"25", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire"] },
  { id:"solar-tomato", en:"Solar Tomato", name:"Солнечный томат", icon:"☀️", sun:"100", recharge:"25", world:"Seed Packets", worldRu:"Пакеты семян", types:["sun"] },
  { id:"shadow-peashooter", en:"Shadow Peashooter", name:"Теневой горохострел", icon:"🌑", sun:"125", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["shadow","pea"] },
  { id:"goo-peashooter", en:"Goo Peashooter", name:"Слизистый горохострел", icon:"🟢", sun:"125", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["pea","poison"] },
  { id:"sling-pea", en:"Sling Pea", name:"Рогаточный горох", icon:"🟢", sun:"125", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["pea"] },
  { id:"snap-pea", en:"Snap Pea", name:"Гороховая хватка", icon:"🟢", sun:"200", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["pea"] },
  { id:"zoybean-pod", en:"Zoybean Pod", name:"Зомбо-стручок", icon:"🌱", sun:"200", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"dazey-chain", en:"Dazey Chain", name:"Оглушающая цепь", icon:"🌱", sun:"150", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"electrici-tea", en:"Electrici-tea", name:"Электрочай", icon:"⚡", sun:"125", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["electric"] },
  { id:"blastberry-vine", en:"Blastberry Vine", name:"Взрывоягодная лоза", icon:"🌱", sun:"175", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"pokra", en:"Pokra", name:"Покра", icon:"👊", sun:"175", recharge:"7", world:"Seed Packets", worldRu:"Пакеты семян", types:["melee"] },
  { id:"imp-pear", en:"Imp Pear", name:"Чертёнок-груша", icon:"🟢", sun:"0", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["pea","support"] },
  { id:"pumpkin", en:"Pumpkin", name:"Тыква", icon:"🛡️", sun:"150", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["defense"] },
  { id:"pyre-vine", en:"Pyre Vine", name:"Огненная лоза", icon:"🔥", sun:"125", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire"] },
  { id:"ice-bloom", en:"Ice Bloom", name:"Ледяной бутон", icon:"🧊", sun:"200", recharge:"25", world:"Seed Packets", worldRu:"Пакеты семян", types:["ice"] },
  { id:"dartichoke", en:"Dartichoke", name:"Дартишок", icon:"🌱", sun:"225", recharge:"8.5", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"ultomato", en:"Ultomato", name:"Ультомат", icon:"🌱", sun:"250", recharge:"6.5", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"gumnut", en:"Gumnut", name:"Смоляной орех", icon:"🛡️", sun:"125", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["defense"] },
  { id:"shine-vine", en:"Shine Vine", name:"Сияющая лоза", icon:"☀️", sun:"75", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["sun"] },
  { id:"tumbleweed", en:"Tumbleweed", name:"Перекати-поле", icon:"🌱", sun:"50", recharge:"5.5", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"olive-pit", en:"Olive Pit", name:"Оливковая яма", icon:"🌱", sun:"175", recharge:"7", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"puffball", en:"Puffball", name:"Дождевик", icon:"☠️", sun:"150", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["poison"] },
  { id:"explode-o-vine", en:"Explode-o-Vine", name:"Взрывная лоза", icon:"💣", sun:"150", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb"] },
  { id:"murkadamia-nut", en:"Murkadamia Nut", name:"Мрачный орех", icon:"🌑", sun:"100", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["shadow"] },
  { id:"turkey-pult", en:"Turkey-pult", name:"Индеевомёт", icon:"🎯", sun:"150", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["lobber"] },
  { id:"headbutter-lettuce", en:"Headbutter Lettuce", name:"Салат-боксёр", icon:"👊", sun:"175", recharge:"7", world:"Seed Packets", worldRu:"Пакеты семян", types:["melee"] },
  { id:"boingsetta", en:"Boingsetta", name:"Прыгунсетта", icon:"🌱", sun:"150", recharge:"30", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"stickybomb-rice", en:"Stickybomb Rice", name:"Липкорисовая бомба", icon:"🧊", sun:"225", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["ice","bomb"] },
  { id:"hocus-crocus", en:"Hocus Crocus", name:"Фокус-крокус", icon:"✨", sun:"200", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["support"] },
  { id:"gloom-vine", en:"Gloom Vine", name:"Мрачная лоза", icon:"🌑", sun:"125", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["shadow"] },
  { id:"draftodil", en:"Draftodil", name:"Сквозняковый нарцисс", icon:"🌱", sun:"100", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"boom-balloon-flower", en:"Boom Balloon Flower", name:"Шаро-цветок", icon:"💣", sun:"350", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb"] },
  { id:"pea-vine", en:"Pea Vine", name:"Гороховая лоза", icon:"🟢", sun:"125", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["pea"] },
  { id:"inferno", en:"Inferno", name:"Инферно", icon:"🔥", sun:"200", recharge:"25", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire"] },
  { id:"solar-sage", en:"Solar Sage", name:"Солнечный шалфей", icon:"☀️", sun:"0", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["sun"] },
  { id:"power-vine", en:"Power Vine", name:"Силовая лоза", icon:"🌱", sun:"150", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"noctarine", en:"Noctarine", name:"Ноктарин", icon:"🌑", sun:"150", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["shadow"] },
  { id:"heath-seeker", en:"Heath Seeker", name:"Искатель вереска", icon:"🌱", sun:"125", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"iceweed", en:"Iceweed", name:"Ледосорняк", icon:"🧊", sun:"150", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["ice","spike"] },
  { id:"tiger-grass", en:"Tiger Grass", name:"Тигровая трава", icon:"🌱", sun:"150", recharge:"7", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"teleportato-mine", en:"Teleportato Mine", name:"Телепортато-мина", icon:"💣", sun:"75", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb","support"] },
  { id:"blockoli", en:"Blockoli", name:"Блоколи", icon:"🛡️", sun:"150", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["defense"] },
  { id:"buttercup", en:"Buttercup", name:"Лютик", icon:"🌱", sun:"25", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"bramble-bush", en:"Bramble Bush", name:"Колючий куст", icon:"📌", sun:"125", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["spike"] },
  { id:"rhubarbarian", en:"Rhubarbarian", name:"Ревенварь", icon:"👊", sun:"100", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["melee"] },
  { id:"mega-gatling-pea", en:"Mega Gatling Pea", name:"Мега Гатлинг-горох", icon:"🟢", sun:"400", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["pea"] },
  { id:"levitater", en:"Levitater", name:"Левитатор", icon:"✨", sun:"50", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["support"] },
  { id:"tomb-tangler", en:"Tomb Tangler", name:"Могильный ловец", icon:"✨", sun:"25", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["support"] },
  { id:"vamporcini", en:"Vamporcini", name:"Вампорчини", icon:"🌱", sun:"100", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"meteor-flower", en:"Meteor Flower", name:"Метео-цветок", icon:"🔥", sun:"250", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire"] },
  { id:"chilly-pepper", en:"Chilly Pepper", name:"Ледяной перец", icon:"🔥", sun:"100", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire","ice"] },
  { id:"bun-chi", en:"Bun Chi", name:"Бун-чи", icon:"👊", sun:"150", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["melee"] },
  { id:"bzzz-button", en:"Bzzz Button", name:"Бззз-кнопка", icon:"⚡", sun:"50", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["electric"] },
  { id:"boomberry", en:"BoomBerry", name:"Бум-ягода", icon:"💣", sun:"225", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb"] },
  { id:"maybee", en:"MayBee", name:"Май-пчела", icon:"🌱", sun:"300", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"seaflora", en:"SeaFlora", name:"Морская флора", icon:"🌊", sun:"225", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["water"] },
  { id:"scaredy-shroom", en:"Scaredy-shroom", name:"Трусогриб", icon:"🌑", sun:"25", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["shadow"] },
  { id:"bamboo-spartan", en:"Bamboo Spartan", name:"Бамбук-спартанец", icon:"👊", sun:"175", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["melee"] },
  { id:"sundew-tangler", en:"Sundew Tangler", name:"Росянка-ловец", icon:"🌱", sun:"100", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"bean-sprout", en:"Bean Sprout", name:"Росток боба", icon:"🌱", sun:"75", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"nightcap", en:"Nightcap", name:"Ночной колпак", icon:"🌑", sun:"300", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["shadow"] },
  { id:"cran-jelly", en:"Cran Jelly", name:"Клюквенное желе", icon:"🌱", sun:"75", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"bud-uh-boom", en:"Bud'uh Boom", name:"Бад-ух Бум", icon:"💣", sun:"100", recharge:"35", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb"] },
  { id:"ice-shroom", en:"Ice-shroom", name:"Ледогриб", icon:"🧊", sun:"175", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["ice"] },
  { id:"dragon-bruit", en:"Dragon Bruit", name:"Дракон осеменитель", icon:"🌱", sun:"200", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"electric-peel", en:"Electric Peel", name:"Электро-кожура", icon:"⚡", sun:"125", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["electric"] },
  { id:"sea-shroom", en:"Sea-shroom", name:"Морской гриб", icon:"🌊", sun:"0", recharge:"5", world:"Seed Packets", worldRu:"Пакеты семян", types:["water"] },
  { id:"guard-shroom", en:"Guard-shroom", name:"Гриб-страж", icon:"🛡️", sun:"200", recharge:"30", world:"Seed Packets", worldRu:"Пакеты семян", types:["defense"] },
  { id:"aqua-vine", en:"Aqua Vine", name:"Аква-лоза", icon:"🌊", sun:"125", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["water"] },
  { id:"mangofier", en:"Mangofier", name:"Мангофер", icon:"🌱", sun:"150", recharge:"8", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"blast-spinner", en:"Blast Spinner", name:"Взрывной спиннер", icon:"🌱", sun:"150", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"doom-shroom", en:"Doom-shroom", name:"Гриб судьбы", icon:"💣", sun:"175", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["bomb"] },
  { id:"blaze-leaf", en:"Blaze Leaf", name:"Пламенный лист", icon:"🔥", sun:"175", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire"] },
  { id:"frost-bonnet", en:"Frost Bonnet", name:"Морозный капюшон", icon:"🧊", sun:"175", recharge:"12", world:"Seed Packets", worldRu:"Пакеты семян", types:["ice"] },
  { id:"znake-lily", en:"Znake Lily", name:"Змейная лилия", icon:"🌱", sun:"200", recharge:"45", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"sweetheart-snare", en:"Sweetheart Snare", name:"Ловушка-милашка", icon:"🌱", sun:"175", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"hammeruit", en:"Hammeruit", name:"Молотофрукт", icon:"👊", sun:"200", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["melee"] },
  { id:"corn-fetti-popper", en:"Corn-fetti Popper", name:"Кукурузная хлопушка", icon:"🌱", sun:"175", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"seashooter", en:"Seashooter", name:"Морской стрелок", icon:"🌊", sun:"300", recharge:"8", world:"Seed Packets", worldRu:"Пакеты семян", types:["water"] },
  { id:"devour-bloom", en:"Devour Bloom", name:"Цветок-пожиратель", icon:"🌱", sun:"125", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"sour-shot", en:"Sour Shot", name:"Кислый выстрел", icon:"☠️", sun:"200", recharge:"10", world:"Seed Packets", worldRu:"Пакеты семян", types:["poison"] },
  { id:"brain-stem", en:"Brain Stem", name:"Мозговой стебель", icon:"🌱", sun:"120", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"lemonaid", en:"Lemonaid", name:"Лимонадник", icon:"🌱", sun:"150", recharge:"20", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"rose", en:"Rose", name:"Роза", icon:"🌱", sun:"170", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"blazing-knight", en:"Blazing Knight", name:"Пылающий рыцарь", icon:"🔥", sun:"300", recharge:"15", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire","shadow"] },
  { id:"sakura", en:"Sakura", name:"Сакура", icon:"🌱", sun:"175", recharge:"16", world:"Seed Packets", worldRu:"Пакеты семян", types:["other"] },
  { id:"volt-snapdragon", en:"Volt Snapdragon", name:"Вольт-дракончик", icon:"🔥", sun:"200", recharge:"7", world:"Seed Packets", worldRu:"Пакеты семян", types:["fire","electric"] },
  { id:"thorn-whip", en:"Thorn Whip", name:"Шиповой кнут", icon:"👊", sun:"175", recharge:"14", world:"Seed Packets", worldRu:"Пакеты семян", types:["melee"] },
  { id:"fila-mint", en:"Fila-mint", name:"Фила-мята", icon:"⚡", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["electric","mint"] },
  { id:"pepper-mint", en:"Pepper-mint", name:"Перечная мята", icon:"🔥", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["fire","mint"] },
  { id:"winter-mint", en:"Winter-mint", name:"Зимняя мята", icon:"🧊", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["ice","mint"] },
  { id:"enlighten-mint", en:"Enlighten-mint", name:"Мята просветления", icon:"☀️", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["sun","mint"] },
  { id:"reinforce-mint", en:"Reinforce-mint", name:"Укрепляющая мята", icon:"🛡️", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["defense","mint"] },
  { id:"bombard-mint", en:"Bombard-mint", name:"Бомбардир-мята", icon:"💣", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["bomb","mint"] },
  { id:"ail-mint", en:"Ail-mint", name:"Недуг-мята", icon:"☠️", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["poison","mint"] },
  { id:"enchant-mint", en:"Enchant-mint", name:"Чародейская мята", icon:"🌿", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["mint"] },
  { id:"contain-mint", en:"Contain-mint", name:"Сдерживающая мята", icon:"🌿", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["mint"] },
  { id:"enforce-mint", en:"Enforce-mint", name:"Силовая мята", icon:"🌿", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["mint"] },
  { id:"arma-mint", en:"Arma-mint", name:"Арма-мята", icon:"🌿", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["mint"] },
  { id:"conceal-mint", en:"Conceal-mint", name:"Скрывающая мята", icon:"🌑", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["shadow","mint"] },
  { id:"spear-mint", en:"Spear-mint", name:"Копейная мята", icon:"🟢", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["pea","mint"] },
  { id:"appease-mint", en:"Appease-mint", name:"Умиротворяющая мята", icon:"🟢", sun:"0", recharge:"85", world:"Power Mints", worldRu:"Силовые мяты", types:["pea","mint"] }
];

window.PVZ2_TYPES = [
  { id:"all", name:"Все", icon:"🌱" },
  { id:"fire", name:"Огонь", icon:"🔥" },
  { id:"ice", name:"Лёд", icon:"🧊" },
  { id:"electric", name:"Электричество", icon:"⚡" },
  { id:"shadow", name:"Тень", icon:"🌑" },
  { id:"water", name:"Вода", icon:"🌊" },
  { id:"bomb", name:"Взрыв", icon:"💣" },
  { id:"defense", name:"Защита", icon:"🛡️" },
  { id:"sun", name:"Солнце", icon:"☀️" },
  { id:"pea", name:"Горох", icon:"🟢" },
  { id:"lobber", name:"Метатели", icon:"🎯" },
  { id:"melee", name:"Ближний бой", icon:"👊" },
  { id:"spike", name:"Шипы", icon:"📌" },
  { id:"poison", name:"Яд", icon:"☠️" },
  { id:"support", name:"Поддержка", icon:"✨" },
  { id:"mint", name:"Мяты", icon:"🌿" },
  { id:"other", name:"Прочие", icon:"🌼" }
];
