/**
 * Каналы и ролики. Видео крутятся внутри через YouTube embed (поиск/плейлист).
 * likes / subs — отображаемые счётчики; short — short-ролик.
 */
window.YT_CHANNELS = [
  {
    id: "tri-kota",
    name: "Три кота",
    emoji: "🐱",
    cat: "kids",
    color: "#ff9f43",
    desc: "Коржик, Компот и Карамелька — серии.",
    subs: "12.4 млн",
    likesBase: 840000,
    search: "Три кота мультфильм серия официальный",
    videos: [
      { q: "Три кота новый день", title: "Новый день", likes: "210 тыс." },
      { q: "Три кота сладкоежка", title: "Сладкоежка", likes: "189 тыс." },
      { q: "Три кота прятки", title: "Прятки", likes: "156 тыс." },
      { q: "Три кота волшебная палочка", title: "Волшебная палочка", likes: "142 тыс." },
      { q: "Три кота космос", title: "Космос", likes: "131 тыс." },
      { q: "Три кота shorts", title: "Shorts · Три кота", likes: "98 тыс.", short: true },
    ],
  },
  {
    id: "smeshariki",
    name: "Смешарики",
    emoji: "⚪",
    cat: "kids",
    color: "#74b9ff",
    desc: "Круглые друзья и добрые истории.",
    subs: "8.1 млн",
    likesBase: 620000,
    search: "Смешарики серия полный",
    videos: [
      { q: "Смешарики Крош и Ёжик", title: "Крош и Ёжик", likes: "175 тыс." },
      { q: "Смешарики Бараш", title: "Бараш", likes: "120 тыс." },
      { q: "Смешарики Нюша", title: "Нюша", likes: "110 тыс." },
      { q: "Смешарики Пин-код", title: "Пин-код", likes: "95 тыс." },
      { q: "Смешарики shorts", title: "Shorts · Смешарики", likes: "80 тыс.", short: true },
    ],
  },
  {
    id: "fixiki",
    name: "Фиксики",
    emoji: "🔧",
    cat: "kids",
    color: "#55efc4",
    desc: "Про технику понятно и смешно.",
    subs: "6.7 млн",
    likesBase: 410000,
    search: "Фиксики серия официальный",
    videos: [
      { q: "Фиксики компьютер", title: "Компьютер", likes: "90 тыс." },
      { q: "Фиксики холодильник", title: "Холодильник", likes: "85 тыс." },
      { q: "Фиксики телефон", title: "Телефон", likes: "78 тыс." },
      { q: "Фиксики shorts", title: "Shorts · Фиксики", likes: "60 тыс.", short: true },
    ],
  },
  {
    id: "sladosti",
    name: "Сладости или гадости",
    emoji: "🍬",
    cat: "challenge",
    color: "#fd79a8",
    desc: "Челленджи: угадай, сладкое или гадость?",
    subs: "3.2 млн",
    likesBase: 290000,
    search: "сладости или гадости челлендж",
    videos: [
      { q: "сладости или гадости конфеты", title: "Конфеты челлендж", likes: "220 тыс." },
      { q: "сладости или гадости напитки", title: "Напитки", likes: "180 тыс." },
      { q: "сладости или гадости еда", title: "Еда", likes: "165 тыс." },
      { q: "сладости или гадости shorts", title: "Shorts · челлендж", likes: "140 тыс.", short: true },
      { q: "sweet or sour challenge russian", title: "Sweet or Sour RU", likes: "95 тыс." },
    ],
  },
  {
    id: "poznavatel",
    name: "Познаватель",
    emoji: "🐻",
    cat: "challenge",
    color: "#e17055",
    desc: "Желейный медведь Валера и эксперименты.",
    subs: "14.8 млн",
    likesBase: 980000,
    search: "Познаватель желейный медведь Валера",
    videos: [
      { q: "Познаватель Валера шоколад", title: "Валера и шоколад", likes: "450 тыс." },
      { q: "Познаватель эксперимент", title: "Эксперимент", likes: "380 тыс." },
      { q: "Познаватель новый дом", title: "Новый дом", likes: "310 тыс." },
      { q: "Познаватель Желтобрюх", title: "Желтобрюх", likes: "290 тыс." },
      { q: "Познаватель shorts", title: "Shorts · Познаватель", likes: "200 тыс.", short: true },
    ],
  },
  {
    id: "fixeye",
    name: "Фиксай",
    emoji: "👁️",
    cat: "blog",
    color: "#00cec9",
    desc: "FixEye — Майнкрафт и приключения.",
    subs: "11.4 млн",
    likesBase: 870000,
    search: "FixEye Майнкрафт",
    videos: [
      { q: "FixEye выживание", title: "Выживание", likes: "520 тыс." },
      { q: "FixEye хардкор", title: "Хардкор", likes: "410 тыс." },
      { q: "FixEye дом", title: "Строим дом", likes: "360 тыс." },
      { q: "FixEye троллинг", title: "Троллинг", likes: "340 тыс." },
      { q: "FixEye shorts", title: "Shorts · Фиксай", likes: "280 тыс.", short: true },
    ],
  },
  {
    id: "yaroks",
    name: "Ярокс Блог",
    emoji: "🚀",
    cat: "blog",
    color: "#a29bfe",
    desc: "Ярокс — игры, влоги и челленджи.",
    subs: "2.1 млн",
    likesBase: 190000,
    search: "Ярокс Блог",
    videos: [
      { q: "Ярокс Блог новое", title: "Новое видео", likes: "85 тыс." },
      { q: "Ярокс челлендж", title: "Челлендж", likes: "72 тыс." },
      { q: "Ярокс Майнкрафт", title: "Майнкрафт", likes: "68 тыс." },
      { q: "Ярокс shorts", title: "Shorts · Ярокс", likes: "55 тыс.", short: true },
    ],
  },
  {
    id: "billient",
    name: "Биллиент",
    emoji: "💎",
    cat: "blog",
    color: "#81ecec",
    desc: "Биллиент — яркие ролики и челленджи.",
    subs: "1.6 млн",
    likesBase: 140000,
    search: "Биллиент YouTube",
    videos: [
      { q: "Биллиент челлендж", title: "Челлендж", likes: "64 тыс." },
      { q: "Биллиент игры", title: "Игры", likes: "51 тыс." },
      { q: "Биллиент shorts", title: "Shorts · Биллиент", likes: "40 тыс.", short: true },
    ],
  },
  {
    id: "vladus",
    name: "Владус",
    emoji: "🟩",
    cat: "blog",
    color: "#55efc4",
    desc: "Владус — Майнкрафт, приколы и сюжеты.",
    subs: "4.5 млн",
    likesBase: 520000,
    search: "Владус Майнкрафт",
    videos: [
      { q: "Владус прятки Майнкрафт", title: "Прятки", likes: "310 тыс." },
      { q: "Владус скулбой", title: "Скулбой", likes: "280 тыс." },
      { q: "Владус база", title: "Секретная база", likes: "250 тыс." },
      { q: "Владус shorts", title: "Shorts · Владус", likes: "190 тыс.", short: true },
    ],
  },
  {
    id: "marmeladus",
    name: "Владус Мармеладус",
    emoji: "🍭",
    cat: "blog",
    color: "#ff7675",
    desc: "Мармеладус — сладкий вайб и Майнкрафт.",
    subs: "3.8 млн",
    likesBase: 460000,
    search: "Владус Мармеладус Майнкрафт",
    videos: [
      { q: "Владус Мармеладус троллинг", title: "Троллинг", likes: "270 тыс." },
      { q: "Владус Мармеладус выживание", title: "Выживание", likes: "240 тыс." },
      { q: "Владус Мармеладус дом", title: "Дом", likes: "210 тыс." },
      { q: "Владус Мармеладус shorts", title: "Shorts", likes: "160 тыс.", short: true },
    ],
  },
  {
    id: "vlada4",
    name: "Vlad A4",
    emoji: "🔥",
    cat: "challenge",
    color: "#e17055",
    desc: "Челленджи и безумные эксперименты.",
    subs: "48 млн",
    likesBase: 2100000,
    search: "Vlad A4 челлендж",
    videos: [
      { q: "Vlad A4 24 часа", title: "24 часа", likes: "1.2 млн" },
      { q: "Vlad A4 эксперимент", title: "Эксперимент", likes: "980 тыс." },
      { q: "Vlad A4 дом", title: "Дом", likes: "870 тыс." },
      { q: "Vlad A4 shorts", title: "Shorts · A4", likes: "650 тыс.", short: true },
    ],
  },
  {
    id: "sakvashin",
    name: "Саквашин",
    emoji: "🎮",
    cat: "blog",
    color: "#6c5ce7",
    desc: "Игры и прохождения.",
    subs: "1.9 млн",
    likesBase: 170000,
    search: "Саквашин",
    videos: [
      { q: "Саквашин прохождение", title: "Прохождение", likes: "70 тыс." },
      { q: "Саквашин новое", title: "Новое", likes: "58 тыс." },
      { q: "Саквашин shorts", title: "Shorts", likes: "42 тыс.", short: true },
    ],
  },
  {
    id: "mrbeast",
    name: "MrBeast",
    emoji: "💰",
    cat: "challenge",
    color: "#00b894",
    desc: "Большие призы и челленджи.",
    subs: "320 млн",
    likesBase: 8900000,
    search: "MrBeast challenge",
    videos: [
      { q: "MrBeast $1 vs $1,000,000", title: "$1 vs $1,000,000", likes: "12 млн" },
      { q: "MrBeast 50 hours", title: "50 hours", likes: "8 млн" },
      { q: "MrBeast shorts", title: "Shorts · Beast", likes: "5 млн", short: true },
    ],
  },
  {
    id: "gravity",
    name: "Gravity Falls",
    emoji: "🌲",
    cat: "toon",
    color: "#6c5ce7",
    desc: "Гравити Фолз — тайны и приключения.",
    subs: "2.4 млн",
    likesBase: 300000,
    search: "Gravity Falls русская озвучка серия",
    videos: [
      { q: "Gravity Falls 1 серия русская", title: "1 серия", likes: "190 тыс." },
      { q: "Gravity Falls Диппер", title: "Диппер и Мейбл", likes: "160 тыс." },
      { q: "Gravity Falls shorts", title: "Shorts", likes: "90 тыс.", short: true },
    ],
  },
  {
    id: "anime-draw",
    name: "Рисуем аниме",
    emoji: "✏️",
    cat: "toon",
    color: "#fd79a8",
    desc: "Уроки рисовки аниме.",
    subs: "890 тыс.",
    likesBase: 95000,
    search: "как рисовать аниме урок",
    videos: [
      { q: "как рисовать аниме лицо", title: "Лицо", likes: "48 тыс." },
      { q: "как рисовать аниме глаза", title: "Глаза", likes: "41 тыс." },
      { q: "аниме рисунок shorts", title: "Shorts · рисовка", likes: "33 тыс.", short: true },
    ],
  },
  {
    id: "amal-room",
    name: "Канал Amal",
    emoji: "🌙",
    cat: "mine",
    color: "#f0b429",
    desc: "Твои ролики — даже черновики без YouTube.",
    subs: "ты",
    likesBase: 67,
    allowUpload: true,
    search: "",
    videos: [],
  },
];
