/**
 * Настоящие ролики (YouTube id) + превью hqdefault + иконка канала = превью первого видео.
 * uploads — лента загрузок канала (fallback).
 */
window.YT_CHANNELS = [
  {
    id: "tri-kota",
    name: "Три кота",
    emoji: "🐱",
    color: "#ff9f43",
    desc: "Коржик, Компот и Карамелька.",
    subs: "12.4 млн",
    channelId: "UCdSaNPMpj-Vi_SF6_MAFpSw",
    uploads: "UUdSaNPMpj-Vi_SF6_MAFpSw",
    icon: "https://i.ytimg.com/vi/e3ZCD4-IcYU/hqdefault.jpg",
    videos: [
      { id: "e3ZCD4-IcYU", title: "Сборник забавных серий", likes: "210 тыс.", thumb: "https://i.ytimg.com/vi/e3ZCD4-IcYU/hqdefault.jpg" },
      { id: "m84_R74FF8A", title: "Сборник крутых серий", likes: "189 тыс.", thumb: "https://i.ytimg.com/vi/m84_R74FF8A/hqdefault.jpg" },
      { id: "VNPM-aPTU0s", title: "Город профессий · №264", likes: "156 тыс.", thumb: "https://i.ytimg.com/vi/VNPM-aPTU0s/hqdefault.jpg" },
      { id: "GR-NO6frapQ", title: "Сборник хороших серий", likes: "142 тыс.", thumb: "https://i.ytimg.com/vi/GR-NO6frapQ/hqdefault.jpg" },
      { id: "uRxLwQJ6HUo", title: "Сборник лучших серий", likes: "131 тыс.", thumb: "https://i.ytimg.com/vi/uRxLwQJ6HUo/hqdefault.jpg" },
      { id: "9CG4OPkkUI0", title: "Неожиданное приключение · №263", likes: "120 тыс.", thumb: "https://i.ytimg.com/vi/9CG4OPkkUI0/hqdefault.jpg" },
      { id: "7J4fHKSrFb8", title: "Сборник отличных серий", likes: "110 тыс.", thumb: "https://i.ytimg.com/vi/7J4fHKSrFb8/hqdefault.jpg" },
      { id: "ywSX7eDX4ys", title: "Сборник милых серий", likes: "98 тыс.", thumb: "https://i.ytimg.com/vi/ywSX7eDX4ys/hqdefault.jpg" },
    ],
  },
  {
    id: "tri-beach",
    name: "Три кота · Море",
    emoji: "🏖️",
    color: "#74b9ff",
    desc: "«Море приключений» — пляж, отель, крабы. Длинный фильм: 3 плавные части.",
    subs: "12.4 млн",
    channelId: "UCdSaNPMpj-Vi_SF6_MAFpSw",
    uploads: "UUdSaNPMpj-Vi_SF6_MAFpSw",
    icon: "https://i.ytimg.com/vi/DaxOiwZWinI/hqdefault.jpg",
    featured: true,
    videos: [
      { id: "DaxOiwZWinI", title: "Часть 1 · Пляж и курорт", likes: "1.1 млн", thumb: "https://i.ytimg.com/vi/DaxOiwZWinI/hqdefault.jpg", part: 1 },
      { id: "NNgzdVPs2lo", title: "Часть 2 · Друзья-крабы", likes: "980 тыс.", thumb: "https://i.ytimg.com/vi/NNgzdVPs2lo/hqdefault.jpg", part: 2 },
      { id: "xzTa9n6RTHM", title: "Часть 3 · Спасение", likes: "870 тыс.", thumb: "https://i.ytimg.com/vi/xzTa9n6RTHM/hqdefault.jpg", part: 3 },
      { id: "QzIhBdmlGBc", title: "Трейлер · Море приключений", likes: "650 тыс.", thumb: "https://i.ytimg.com/vi/QzIhBdmlGBc/hqdefault.jpg" },
      { id: "playlist", title: "▶ Вся лента «Три кота»", playlist: "UUdSaNPMpj-Vi_SF6_MAFpSw", likes: "—", thumb: "https://i.ytimg.com/vi/e3ZCD4-IcYU/hqdefault.jpg" },
    ],
  },
  {
    id: "fixiki",
    name: "Фиксики",
    emoji: "🔧",
    color: "#55efc4",
    desc: "Симка, Нолик и техника.",
    subs: "6.7 млн",
    channelId: "UCQwhrUICcnNKKCDrw6SpHfQ",
    uploads: "UUQwhrUICcnNKKCDrw6SpHfQ",
    icon: "https://i.ytimg.com/vi/F1Jz-tkqlqw/hqdefault.jpg",
    videos: [
      { id: "F1Jz-tkqlqw", title: "Фикси-танцы для мальчиков", likes: "90 тыс.", thumb: "https://i.ytimg.com/vi/F1Jz-tkqlqw/hqdefault.jpg" },
      { id: "Dfhxtpbe-SU", title: "Шарики и пузыри", likes: "85 тыс.", thumb: "https://i.ytimg.com/vi/Dfhxtpbe-SU/hqdefault.jpg" },
      { id: "vd4oKOEnZ-c", title: "Старые добрые Фиксики", likes: "78 тыс.", thumb: "https://i.ytimg.com/vi/vd4oKOEnZ-c/hqdefault.jpg" },
      { id: "iN-N6NaU6nM", title: "Огненная зарядка", likes: "70 тыс.", thumb: "https://i.ytimg.com/vi/iN-N6NaU6nM/hqdefault.jpg" },
      { id: "sjGb5Xc5P4U", title: "Опыты с фиксиками", likes: "65 тыс.", thumb: "https://i.ytimg.com/vi/sjGb5Xc5P4U/hqdefault.jpg" },
      { id: "pTD_L4WoKAI", title: "Фикси-танцы для девочек", likes: "60 тыс.", thumb: "https://i.ytimg.com/vi/pTD_L4WoKAI/hqdefault.jpg", short: true },
    ],
  },
  {
    id: "poznavatel",
    name: "Познаватель",
    emoji: "🐻",
    color: "#e17055",
    desc: "Желейный медведь Валера и эксперименты.",
    subs: "14.8 млн",
    channelId: "UCxC9uLBMn87jl0p5ZmkmQtQ",
    uploads: "UUxC9uLBMn87jl0p5ZmkmQtQ",
    icon: "https://i.ytimg.com/vi/aAl6EaklUas/hqdefault.jpg",
    videos: [
      { id: "aAl6EaklUas", title: "Кинокомпания Познаватель", likes: "450 тыс.", thumb: "https://i.ytimg.com/vi/aAl6EaklUas/hqdefault.jpg" },
      { id: "2feRko_uRhw", title: "Новое · Валера", likes: "380 тыс.", thumb: "https://i.ytimg.com/vi/2feRko_uRhw/hqdefault.jpg" },
      { id: "XvwEVqxr_zs", title: "Свежий ролик", likes: "310 тыс.", thumb: "https://i.ytimg.com/vi/XvwEVqxr_zs/hqdefault.jpg" },
      { id: "atkWvVwvHnc", title: "Новые интро", likes: "290 тыс.", thumb: "https://i.ytimg.com/vi/atkWvVwvHnc/hqdefault.jpg" },
      { id: "playlist", title: "▶ Вся лента канала", playlist: "UUxC9uLBMn87jl0p5ZmkmQtQ", likes: "—", thumb: "https://i.ytimg.com/vi/aAl6EaklUas/hqdefault.jpg" },
    ],
  },
  {
    id: "fixeye",
    name: "Фиксай",
    emoji: "👁️",
    color: "#00cec9",
    desc: "FixEye — Майнкрафт и приключения.",
    subs: "11.4 млн",
    channelId: "UCCiGUQiWcz3lKev49TX8-Ew",
    uploads: "UUCiGUQiWcz3lKev49TX8-Ew",
    icon: "https://i.ytimg.com/vi/p4EGCtGtGOg/hqdefault.jpg",
    videos: [
      { id: "p4EGCtGtGOg", title: "Хоррор моды · ломается всё", likes: "520 тыс.", thumb: "https://i.ytimg.com/vi/p4EGCtGtGOg/hqdefault.jpg" },
      { id: "Nx7fMpNONuY", title: "DreamShift · Бэкрумс 3", likes: "410 тыс.", thumb: "https://i.ytimg.com/vi/Nx7fMpNONuY/hqdefault.jpg" },
      { id: "2V3IEeoaCcY", title: "SCP Обсессия", likes: "360 тыс.", thumb: "https://i.ytimg.com/vi/2V3IEeoaCcY/hqdefault.jpg" },
      { id: "_pPkQYu-tms", title: "DreamShift · часть 2", likes: "340 тыс.", thumb: "https://i.ytimg.com/vi/_pPkQYu-tms/hqdefault.jpg" },
      { id: "IK4gMklgJTk", title: "Девушка-сталкер SCP", likes: "300 тыс.", thumb: "https://i.ytimg.com/vi/IK4gMklgJTk/hqdefault.jpg" },
      { id: "n28_PMhXVDQ", title: "Из блоков — оружие", likes: "280 тыс.", thumb: "https://i.ytimg.com/vi/n28_PMhXVDQ/hqdefault.jpg", short: true },
    ],
  },
  {
    id: "vladus",
    name: "Владус",
    emoji: "🟩",
    color: "#55efc4",
    desc: "Владус Мармеладус — Майнкрафт и сюжеты.",
    subs: "4.5 млн",
    channelId: "UCPG6OP7eL7kLuyFpQMdqYSA",
    uploads: "UUPG6OP7eL7kLuyFpQMdqYSA",
    icon: "https://i.ytimg.com/vi/kMw7JqwwLTk/hqdefault.jpg",
    videos: [
      { id: "kMw7JqwwLTk", title: "Мир Смешариков в Роблокс", likes: "310 тыс.", thumb: "https://i.ytimg.com/vi/kMw7JqwwLTk/hqdefault.jpg" },
      { id: "zi2Ncyx2Wes", title: "Уменьшиться чтобы победить", likes: "280 тыс.", thumb: "https://i.ytimg.com/vi/zi2Ncyx2Wes/hqdefault.jpg" },
      { id: "mc6ADlxk254", title: "Инвентарь друга", likes: "250 тыс.", thumb: "https://i.ytimg.com/vi/mc6ADlxk254/hqdefault.jpg" },
      { id: "7onAAdWhxdg", title: "5 минут от Верити", likes: "240 тыс.", thumb: "https://i.ytimg.com/vi/7onAAdWhxdg/hqdefault.jpg" },
      { id: "RiyBfsB67rQ", title: "Злой клон скопировал планету", likes: "220 тыс.", thumb: "https://i.ytimg.com/vi/RiyBfsB67rQ/hqdefault.jpg", short: true },
      { id: "r412FSnL9N0", title: "Не строй гигантского Верити", likes: "200 тыс.", thumb: "https://i.ytimg.com/vi/r412FSnL9N0/hqdefault.jpg" },
    ],
  },
  {
    id: "vlada4",
    name: "Vlad A4",
    emoji: "🔥",
    color: "#e17055",
    desc: "Челленджи и эксперименты.",
    subs: "48 млн",
    channelId: "UC2tsySbe9TNrI-xh2lximHA",
    uploads: "UU2tsySbe9TNrI-xh2lximHA",
    icon: "https://i.ytimg.com/vi/lq1-d6tOJ9E/hqdefault.jpg",
    videos: [
      { id: "lq1-d6tOJ9E", title: "Новогодняя тарелка челлендж", likes: "1.2 млн", thumb: "https://i.ytimg.com/vi/lq1-d6tOJ9E/hqdefault.jpg" },
      { id: "3UUQW75qOok", title: "Cheese Tower vs Mice", likes: "980 тыс.", thumb: "https://i.ytimg.com/vi/3UUQW75qOok/hqdefault.jpg" },
      { id: "ryjBDG2RnTg", title: "3 SECRET Rooms", likes: "870 тыс.", thumb: "https://i.ytimg.com/vi/ryjBDG2RnTg/hqdefault.jpg" },
      { id: "UxnhAdUKark", title: "Extreme CAMOUFLAGE", likes: "800 тыс.", thumb: "https://i.ytimg.com/vi/UxnhAdUKark/hqdefault.jpg" },
      { id: "zxwOJnynX_E", title: "Candy Into the Cinema", likes: "650 тыс.", thumb: "https://i.ytimg.com/vi/zxwOJnynX_E/hqdefault.jpg", short: true },
      { id: "LtuLgcEGrMc", title: "А вы уже пробовали?", likes: "500 тыс.", thumb: "https://i.ytimg.com/vi/LtuLgcEGrMc/hqdefault.jpg", short: true },
    ],
  },
  {
    id: "mrbeast",
    name: "MrBeast",
    emoji: "💰",
    color: "#00b894",
    desc: "Большие призы и челленджи.",
    subs: "320 млн",
    channelId: "UCX6OQ3DkcsbYNE6H8uQQuVA",
    uploads: "UUX6OQ3DkcsbYNE6H8uQQuVA",
    icon: "https://i.ytimg.com/vi/Qtl8lJwbd4g/hqdefault.jpg",
    videos: [
      { id: "Qtl8lJwbd4g", title: "Escape 100 Cops", likes: "12 млн", thumb: "https://i.ytimg.com/vi/Qtl8lJwbd4g/hqdefault.jpg" },
      { id: "Af6i6ChAVTw", title: "Last To Leave Mansion", likes: "8 млн", thumb: "https://i.ytimg.com/vi/Af6i6ChAVTw/hqdefault.jpg" },
      { id: "5mU6SRS2Bxo", title: "World's Largest Tennis", likes: "5 млн", thumb: "https://i.ytimg.com/vi/5mU6SRS2Bxo/hqdefault.jpg" },
      { id: "lVylRtlPOIE", title: "100 Kids Biggest Wish", likes: "4 млн", thumb: "https://i.ytimg.com/vi/lVylRtlPOIE/hqdefault.jpg" },
      { id: "egvLKQe6I4I", title: "Don't Pop the Balloon", likes: "3 млн", thumb: "https://i.ytimg.com/vi/egvLKQe6I4I/hqdefault.jpg", short: true },
    ],
  },
  {
    id: "sladosti",
    name: "Сладости или гадости",
    emoji: "🍬",
    color: "#fd79a8",
    desc: "Челленджи: сладкое или гадость?",
    subs: "3.2 млн",
    channelId: "UC2tsySbe9TNrI-xh2lximHA",
    uploads: "UU2tsySbe9TNrI-xh2lximHA",
    icon: "https://i.ytimg.com/vi/lq1-d6tOJ9E/hqdefault.jpg",
    videos: [
      { id: "lq1-d6tOJ9E", title: "Тарелка челлендж", likes: "220 тыс.", thumb: "https://i.ytimg.com/vi/lq1-d6tOJ9E/hqdefault.jpg" },
      { id: "UxnhAdUKark", title: "Камуфляж челлендж", likes: "180 тыс.", thumb: "https://i.ytimg.com/vi/UxnhAdUKark/hqdefault.jpg" },
      { id: "zxwOJnynX_E", title: "Сладости в кино", likes: "140 тыс.", thumb: "https://i.ytimg.com/vi/zxwOJnynX_E/hqdefault.jpg", short: true },
    ],
  },
  {
    id: "yaroks",
    name: "Ярокс Блог",
    emoji: "🚀",
    color: "#a29bfe",
    desc: "Игры и челленджи (лента похожих).",
    subs: "2.1 млн",
    channelId: "UCCiGUQiWcz3lKev49TX8-Ew",
    uploads: "UUCiGUQiWcz3lKev49TX8-Ew",
    icon: "https://i.ytimg.com/vi/p4EGCtGtGOg/hqdefault.jpg",
    videos: [
      { id: "p4EGCtGtGOg", title: "Новое видео", likes: "85 тыс.", thumb: "https://i.ytimg.com/vi/p4EGCtGtGOg/hqdefault.jpg" },
      { id: "Nx7fMpNONuY", title: "Челлендж", likes: "72 тыс.", thumb: "https://i.ytimg.com/vi/Nx7fMpNONuY/hqdefault.jpg" },
      { id: "playlist", title: "▶ Лента", playlist: "UUCiGUQiWcz3lKev49TX8-Ew", likes: "—", thumb: "https://i.ytimg.com/vi/p4EGCtGtGOg/hqdefault.jpg" },
    ],
  },
  {
    id: "amal-room",
    name: "Канал Amal",
    emoji: "🌙",
    color: "#f0b429",
    desc: "Твои ролики — даже черновики без YouTube.",
    subs: "ты",
    allowUpload: true,
    icon: "",
    videos: [],
  },
];
